import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { httpBaseUrl, portalUrl } from "@/lib/env";
import { FLYER_LINK_SECONDS, flyerLoadError, flyerRef, flyerSourceLabel, portalFlyerLink } from "@/lib/logic/event-flyer";

// The Server Action is exercised with its session and Next.js plumbing stubbed out, so the test can
// read the exact payload it sends to app.events.
const { db, CENTER, EVENT } = vi.hoisted(() => ({
  db: { payloads: [] as Record<string, unknown>[] },
  CENTER: "00000000-0000-4000-8000-000000000001",
  EVENT: "6f1c2b9e-4d3a-4c55-9a1e-2b7d8f0e1a23",
}));
vi.mock("next/cache", () => ({ refresh: vi.fn() }));
vi.mock("next/navigation", () => ({
  redirect: vi.fn(),
  unstable_rethrow: vi.fn(),
}));
vi.mock("@/lib/action-context", () => ({
  actionContext: vi.fn(async () => {
    const chain = {
      update(values: Record<string, unknown>) {
        db.payloads.push(values);
        return chain;
      },
      insert(values: Record<string, unknown>) {
        db.payloads.push(values);
        return chain;
      },
      eq: () => chain,
      select: () => chain,
      single: async () => ({ data: { id: EVENT }, error: null }),
      then: (resolve: (v: unknown) => unknown) => resolve({ data: [{ id: EVENT }], error: null }),
    };
    return {
      supabase: { from: () => chain },
      centerId: CENTER,
      viewer: { userId: "00000000-0000-4000-8000-0000000000aa" },
      tz: "America/Chicago",
    };
  }),
}));

const KEY = `${CENTER}/events/${EVENT}/flyer-1759300000000.png`;

describe("flyerRef", () => {
  it("is none for null, empty or whitespace", () => {
    expect(flyerRef(null)).toEqual({ kind: "none" });
    expect(flyerRef(undefined)).toEqual({ kind: "none" });
    expect(flyerRef("")).toEqual({ kind: "none" });
    expect(flyerRef("   \n")).toEqual({ kind: "none" });
  });
  it("uses an https link as is", () => {
    expect(flyerRef(" https://cdn.example.org/flyers/diwali.png ")).toEqual({ kind: "url", url: "https://cdn.example.org/flyers/diwali.png" });
    expect(flyerRef("HTTPS://cdn.example.org/a.png?x=1")).toEqual({ kind: "url", url: "HTTPS://cdn.example.org/a.png?x=1" });
  });
  it("rejects an http link and every other scheme (never treated as a storage key)", () => {
    expect(flyerRef("http://cdn.example.org/flyer.png")).toEqual({ kind: "none" });
    expect(flyerRef("javascript:alert(1)")).toEqual({ kind: "none" });
    expect(flyerRef("data:image/png;base64,AAAA")).toEqual({ kind: "none" });
    expect(flyerRef("https://")).toEqual({ kind: "none" });
  });
  it("strips a leading content/ bucket prefix or slash from a storage key", () => {
    expect(flyerRef(`content/${KEY}`)).toEqual({ kind: "storage", key: KEY });
    expect(flyerRef(`/${KEY}`)).toEqual({ kind: "storage", key: KEY });
    expect(flyerRef(`/content/${KEY}`)).toEqual({ kind: "storage", key: KEY });
    expect(flyerRef("content/")).toEqual({ kind: "none" });
  });
  it("keeps a bare key", () => {
    expect(flyerRef(KEY)).toEqual({ kind: "storage", key: KEY });
    const uploaded = `${CENTER}/events/${EVENT}/flyer-1759300000000-paryushan-2026.jpg`;
    expect(flyerRef(uploaded)).toEqual({ kind: "storage", key: uploaded });
  });
});

describe("flyerSourceLabel", () => {
  it("names each source the portal writes, and nothing else", () => {
    expect(flyerSourceLabel("designed")).toBe("Made with the portal's flyer maker");
    expect(flyerSourceLabel("manual")).toBe("Uploaded");
    expect(flyerSourceLabel("ai")).toBe("Generated by AI (earlier flyer)");
    expect(flyerSourceLabel(null)).toBeNull();
    expect(flyerSourceLabel(undefined)).toBeNull();
    expect(flyerSourceLabel("something-new")).toBeNull();
  });
});

describe("portalFlyerLink", () => {
  it("builds the event builder link, scrolled to the Flyer card", () => {
    expect(portalFlyerLink("https://portal.example.org", EVENT)).toBe(`https://portal.example.org/events/builder?event=${EVENT}#flyer`);
  });
  it("trims trailing slashes and spaces from the base", () => {
    expect(portalFlyerLink(" https://portal.example.org/ ", EVENT)).toBe(`https://portal.example.org/events/builder?event=${EVENT}#flyer`);
    expect(portalFlyerLink("http://134.122.25.56:8080//", EVENT)).toBe(`http://134.122.25.56:8080/events/builder?event=${EVENT}#flyer`);
  });
  it("is null for a base that is not an http(s) URL", () => {
    for (const base of [null, undefined, "", "portal.example.org", "ftp://portal.example.org", "javascript:alert(1)", "https://", "https://portal.example.org?x=1", "https://portal .org"]) {
      expect(portalFlyerLink(base, EVENT)).toBeNull();
    }
  });
  it("is null for an event id that is not a uuid", () => {
    expect(portalFlyerLink("https://portal.example.org", "not-a-uuid")).toBeNull();
    expect(portalFlyerLink("https://portal.example.org", `${EVENT}&x=1`)).toBeNull();
    expect(portalFlyerLink("https://portal.example.org", "")).toBeNull();
  });
});

describe("portalUrl", () => {
  afterEach(() => {
    vi.unstubAllEnvs();
  });
  it("reads NEXT_PUBLIC_PORTAL_URL, trimmed and without a trailing slash", () => {
    vi.stubEnv("NEXT_PUBLIC_PORTAL_URL", "  https://portal.example.org/  ");
    expect(portalUrl()).toBe("https://portal.example.org");
    vi.stubEnv("NEXT_PUBLIC_PORTAL_URL", "http://localhost:3000");
    expect(portalUrl()).toBe("http://localhost:3000");
  });
  it("is null when unset, blank or not a URL", () => {
    vi.stubEnv("NEXT_PUBLIC_PORTAL_URL", undefined);
    expect(portalUrl()).toBeNull();
    for (const bad of ["", "   ", "portal.example.org", "mailto:office@example.org", "https://"]) {
      vi.stubEnv("NEXT_PUBLIC_PORTAL_URL", bad);
      expect(portalUrl()).toBeNull();
    }
  });
  it("shares its rule with the base the link builder accepts", () => {
    expect(httpBaseUrl("https://portal.example.org/connect/")).toBe("https://portal.example.org/connect");
    expect(httpBaseUrl("https://portal.example.org#top")).toBeNull();
  });
});

describe("flyerLoadError", () => {
  it("explains the usual storage failures in plain English", () => {
    expect(flyerLoadError({ name: "StorageApiError", message: "Object not found", status: 400, statusCode: "404" })).toBe(
      "Could not load the flyer — the image file wasn't found, or you don't have access to it. Make or change the flyer in the portal.",
    );
    expect(flyerLoadError({ name: "StorageApiError", message: "jwt expired", status: 400, statusCode: "403" })).toMatch(/^Could not load the flyer — you don't have access to it, or your session has ended/);
    expect(flyerLoadError({ name: "StorageUnknownError", message: "fetch failed" })).toBe(
      "Could not load the flyer — the file server can't be reached. Check your connection and try again.",
    );
    expect(flyerLoadError(new Error("Something odd."))).toBe("Could not load the flyer — Something odd.");
    expect(flyerLoadError(null)).toBe("Could not load the flyer — something went wrong. Please try again.");
  });
  it("signs for ten minutes", () => {
    expect(FLYER_LINK_SECONDS).toBe(600);
  });
});

describe("saving the event form never writes the flyer", () => {
  beforeEach(() => {
    db.payloads.length = 0;
  });

  function form(extra: Record<string, string> = {}) {
    const fd = new FormData();
    fd.set("name", "Paryushan Mahaparva");
    fd.set("venue", "JSH Derasar");
    fd.set("audience", "members_and_guests");
    for (const [k, v] of Object.entries(extra)) fd.set(k, v);
    return fd;
  }

  const FLYER_COLUMNS = ["flyer_path", "flyer_source", "flyer_prompt", "flyer_design", "flyer_generated_at", "flyer_job_id"];

  it("updateEvent sends no flyer_* key, even when an old form still posts flyer_path", async () => {
    const { updateEvent } = await import("@/app/(console)/events/actions");
    for (const fd of [form(), form({ flyer_path: "content/stale/flyer-1.png" }), form({ flyer_path: "" })]) {
      const res = await updateEvent(EVENT, fd);
      expect(res).toEqual({ ok: true, message: "Event saved.", data: undefined });
    }
    expect(db.payloads).toHaveLength(3);
    for (const payload of db.payloads) {
      expect(payload.name).toBe("Paryushan Mahaparva");
      for (const col of FLYER_COLUMNS) expect(payload).not.toHaveProperty(col);
    }
  });

  it("createEvent sends no flyer_* key", async () => {
    const { createEvent } = await import("@/app/(console)/events/actions");
    await createEvent(form({ flyer_path: "https://cdn.example.org/x.png" }));
    expect(db.payloads).toHaveLength(1);
    expect(db.payloads[0]).toMatchObject({ name: "Paryushan Mahaparva", center_id: CENTER, status: "draft" });
    for (const col of FLYER_COLUMNS) expect(db.payloads[0]).not.toHaveProperty(col);
  });
});
