// The event flyer as this console shows it. Flyers are made in the Community Connect portal
// (connect-crm's flyer maker, which alone writes events.flyer_*); this app only shows the current
// flyer and links there. Pure: no server imports, unit-tested in tests/event-flyer.test.ts.

import { httpBaseUrl } from "@/lib/env";

/** Where events.flyer_path points: nothing, an https link used as is, or a key in the private `content` bucket. */
export type FlyerRef = { kind: "none" } | { kind: "url"; url: string } | { kind: "storage"; key: string };

/** What the Details tab gets for the Flyer card. */
export type FlyerView = {
  /** The image to show (an https link, or a signed link to the stored file), or null. */
  url: string | null;
  /** A plain-English problem to show beside the card, or null. */
  error: string | null;
  /** False when trying again cannot help (the saved value is not something the console can show). */
  retry?: boolean;
  /** True when `url` is a signed link that stops working after FLYER_LINK_SECONDS. */
  signed?: boolean;
};

/** How long a signed flyer link lasts (seconds). A page left open longer needs a reload. */
export const FLYER_LINK_SECONDS = 600;

const NONE: FlyerRef = { kind: "none" };

/**
 * Read events.flyer_path. Keys are stored without the bucket name; older values may carry a
 * `content/` prefix (or a leading slash), which is stripped. Links are https only: an http://
 * image would be blocked on the console's HTTPS pages, and other schemes (javascript:, data:) are
 * never put in an <img>, so anything with a scheme other than https: is rejected (kind "none").
 */
export function flyerRef(path: string | null | undefined): FlyerRef {
  const v = (path ?? "").trim();
  if (!v) return NONE;
  if (/^[a-z][a-z0-9+.-]*:/i.test(v)) {
    return /^https:\/\/[^\s/?#]+[^\s]*$/i.test(v) ? { kind: "url", url: v } : NONE;
  }
  const key = v.replace(/^\/+/, "").replace(/^content\//, "");
  return key ? { kind: "storage", key } : NONE;
}

/** events.flyer_source in words, or null when it is unset or not one the portal writes. */
export function flyerSourceLabel(source: string | null | undefined): string | null {
  switch (source) {
    case "designed":
      return "Made with the portal's flyer maker";
    case "manual":
      return "Uploaded";
    case "ai":
      return "Generated by AI (earlier flyer)";
    default:
      return null;
  }
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * The portal's flyer maker for this event: the event builder, scrolled to its Flyer card
 * (connect-crm renders it with id="flyer"). Null when the portal URL is not an http(s) URL or the
 * event id is not a uuid.
 */
export function portalFlyerLink(base: string | null | undefined, eventId: string): string | null {
  const b = httpBaseUrl(base);
  if (!b || !UUID.test(eventId)) return null;
  return `${b}/events/builder?event=${eventId}#flyer`;
}

/**
 * What to do about a missing or broken flyer. Editors have the portal button on the card; viewers who
 * cannot edit the event do not, so they are pointed at the people who can.
 */
function changeIt(canEdit: boolean): string {
  return canEdit ? "make or change the flyer in the portal" : "ask the event lead or an event manager to make or change it in the portal";
}

function sentence(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/** Shown when flyer_path holds something that is neither an https link nor a stored file. */
export function flyerUnsupported(canEdit: boolean): string {
  return `Could not show the flyer — it is saved as a link the console can't open (only https:// links and files stored in Connect). ${sentence(changeIt(canEdit))} to replace it.`;
}

/** Shown when the image itself does not load in the browser (an expired link, or a file or host that is gone). */
export function flyerImageError(canEdit: boolean): string {
  return `Could not show the flyer image — the link may have expired or the file has moved. Try again, or ${changeIt(canEdit)}.`;
}

/** Shown to editors when there is a flyer: it keeps the words it was made with. */
export const FLYER_STALE_HINT =
  "The flyer shows the details from when it was made. After changing the name, date, time or venue, update it in the portal.";

/** A failed attempt to sign the stored flyer, in plain English (the technical detail is logged separately). */
export function flyerLoadError(error: unknown, canEdit: boolean): string {
  const e = (error && typeof error === "object" ? error : {}) as { message?: unknown; status?: unknown; statusCode?: unknown; name?: unknown };
  const msg = (typeof e.message === "string" ? e.message : error == null ? "" : String(error)).trim();
  const lower = msg.toLowerCase();
  const status = String(e.status ?? "");
  const code = String(e.statusCode ?? "");
  let reason: string;
  if (/jwt|unauthori[sz]ed|permission|row-level security|not allowed/.test(lower) || ["401", "403"].includes(status) || ["401", "403"].includes(code)) {
    reason = "you don't have access to it, or your session has ended. Sign in again, then try again";
  } else if (lower.includes("not found") || status === "404" || code === "404") {
    reason = `the image file wasn't found, or you don't have access to it. ${sentence(changeIt(canEdit))}`;
  } else if (e.name === "StorageUnknownError" || /fetch failed|failed to fetch|network|econn|timed? ?out/.test(lower)) {
    reason = "the file server can't be reached. Check your connection and try again";
  } else {
    reason = msg ? msg.replace(/[.\s]+$/, "") : "something went wrong. Please try again";
  }
  return `Could not load the flyer — ${reason}.`;
}
